# Generated by Django 4.2.6 on 2023-11-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nekta_requests', '0006_remove_requestmessage_user_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmessage',
            name='req',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nekta_requests.request'),
            preserve_default=False,
        ),
    ]
