# Generated by Django 4.2.6 on 2023-11-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nekta_requests', '0007_requestmessage_req'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestmessage',
            old_name='req',
            new_name='request',
        ),
    ]
